"""initial schema

Revision ID: 740ec6de69ee
Revises: 
Create Date: 2025-09-23 15:18:00.049474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '740ec6de69ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quest_templates', sa.Column('requires_place', sa.Boolean(), nullable=False))
    op.add_column('quest_templates', sa.Column('enabled', sa.Boolean(), nullable=False))
    op.add_column('quest_templates', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('quest_templates', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('quest_templates', 'body_template',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=False)
    op.add_column('quests', sa.Column('seed', sa.String(length=64), nullable=True))
    op.add_column('quests', sa.Column('delivered_at', sa.DateTime(), nullable=True))
    op.add_column('submissions', sa.Column('ratings_count', sa.Integer(), nullable=False))
    op.alter_column('submissions', 'caption',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('users', sa.Column('bio', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('avatar_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('webpush_endpoint', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('webpush_keys', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('last_active_at', sa.DateTime(), nullable=True))
    op.add_column('votes', sa.Column('comment', sa.Text(), nullable=True))
    op.add_column('votes', sa.Column('total', sa.Float(), nullable=True))
    op.add_column('votes', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('votes', 'created_at')
    op.drop_column('votes', 'total')
    op.drop_column('votes', 'comment')
    op.drop_column('users', 'last_active_at')
    op.drop_column('users', 'webpush_keys')
    op.drop_column('users', 'webpush_endpoint')
    op.drop_column('users', 'avatar_url')
    op.drop_column('users', 'bio')
    op.alter_column('submissions', 'caption',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('submissions', 'ratings_count')
    op.drop_column('quests', 'delivered_at')
    op.drop_column('quests', 'seed')
    op.alter_column('quest_templates', 'body_template',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    op.drop_column('quest_templates', 'updated_at')
    op.drop_column('quest_templates', 'created_at')
    op.drop_column('quest_templates', 'enabled')
    op.drop_column('quest_templates', 'requires_place')
    # ### end Alembic commands ###