version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sidequest
      POSTGRES_PASSWORD: sidequest
      POSTGRES_DB: sidequest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sidequest"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: ./api
    env_file: .env
    depends_on:
      - db
      - minio
    ports:
      - "8001:8000"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: sidequest
      MINIO_ROOT_PASSWORD: sidequest123
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

  web:
    build: ./web
    depends_on:
      - api
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8001

volumes:
  dbdata:
  minio_data:
