version: "3.9"

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sidequest
      POSTGRES_PASSWORD: sidequest
      POSTGRES_DB: sidequest
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sidequest"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: ./api
    env_file: .env
    depends_on:
      - db
    ports:
      - "8001:8000"

  web:
    build: ./web
    depends_on:
      - api
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:8001

volumes:
  dbdata:
