services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: sidequest
      POSTGRES_PASSWORD: sidequest
      POSTGRES_DB: sidequest
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "sidequest"]

  redis:
    image: redis:7

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    ports:
      - "9001:9001"
    volumes:
      - minio:/data

  api:
    build: ./api
    env_file: .env
    depends_on:
      - db
      - redis
      - minio

  celery:
    build: ./api
    command: celery -A tasks.celery_app worker --loglevel=INFO
    env_file: .env
    depends_on:
      - api
      - redis

  web:
    build: ./web
    volumes:
      - webdist:/dist

  proxy:
    image: nginx:alpine
    volumes:
      - ./ops/nginx.conf:/etc/nginx/nginx.conf:ro
      - webdist:/usr/share/nginx/html:ro
    ports:
      - "8080:80"

volumes:
  dbdata:
  minio:
  webdist: